"""create tables

Revision ID: c3ec88a7853e
Revises: 
Create Date: 2024-10-10 23:28:42.231192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ec88a7853e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table(
        'users',
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('microsoft_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('notes', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('user_id')
    )
        
        op.create_table(
        'subjects',
        sa.Column('subject_id', sa.String(), nullable=False), 
        sa.Column('subject_code', sa.String(), nullable=False),   
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('study_load', sa.Integer(), nullable=False),
        
        sa.PrimaryKeyConstraint('subject_id')
    )
        
        op.create_table(
        'user_subjects',  # Nome da tabela de associação
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.user_id'),  nullable=False),   # Chave estrangeira para a tabela 'users'
        sa.Column('subject_id', sa.String(), sa.ForeignKey('subjects.subject_id'), nullable=False),  # Chave estrangeira para a tabela 'subjects'
        
        # Definindo a chave primária composta
        sa.PrimaryKeyConstraint('user_id', 'subject_id')
    )
    
        op.create_table(
        "calendar",
        sa.Column("calendar_id", sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.user_id'),  nullable=False),   # Chave estrangeira para a tabela 'users'
        sa.Column('subject_id', sa.String(), sa.ForeignKey('subjects.subject_id'), nullable=False),
        sa.Column("dayOfWeek", sa.String(), nullable=False),
        sa.Column("timeSlot", sa.String(), nullable=False),
        
        sa.PrimaryKeyConstraint("calendar_id")
    )
        
        op.create_table(
        'availability',
        sa.Column('availability_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.user_id'),  nullable=False),   # Chave estrangeira para a tabela 'users'
        sa.Column('dayOfWeek', sa.String(), nullable=False),
        sa.Column('status', sa.Boolean(), nullable=False),
        
        sa.PrimaryKeyConstraint('availability_id')
    )
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
