version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: fontys-db
    restart: always
    environment:
      POSTGRES_USER: fontys
      POSTGRES_PASSWORD: fontys
      POSTGRES_DB: fontys
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
