from app.models.users import User
from app.models.user_types import UserType
from app.models.type_users import TypeUser
from app.models.user_shipping import UserShipping
from app.models.user_subjects import UserSubject
from app.models.availabilitys import Availability
from app.models.schedules import Schedule
from app.models.slots import Slot
from app.models.subjects import Subject
from app.models.semesters import Semester
from app.models.courses import Course
from app.models.coordination import Coordination